# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_estimates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estimates',
            new_name='Estimate',
        ),
    ]
