# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20170818_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='complexity',
            field=models.CharField(choices=[(b'HIGH', b'+30 hours'), (b'MEDIUM', b'21-30 hours'), (b'LOW', b'0-20 hours')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='role',
            field=models.CharField(choices=[(b'LEADER', b'Project Leader'), (b'HARDWARE DEVT', b'Hardware developer'), (b'SOFTWARE DEVT', b'Software developer'), (b'PCB', b'PCB Designer'), (b'TESTER', b'Tester'), (b'IMPLEMENTATOR', b'Implementator'), (b'CONF ADMIN', b'Configuration administrator')], max_length=30),
        ),
    ]
