# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20170818_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='required_hours',
            field=models.FloatField(),
        ),
    ]
