# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_auto_20170818_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='percentage_of_completion',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
