# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_auto_20170818_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complexity',
            new_name='task_complexity',
        ),
    ]
