# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_auto_20170818_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='planned_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='real_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='real_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
