# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_auto_20170818_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[(b'QA', b'Quality assurance'), (b'CHANGES', b'Changes'), (b'CLOSURE', b'Project closure'), (b'DEVT', b'Development'), (b'IMPLEMENTATION', b'Implementation'), (b'PLAN', b'Planning'), (b'TEST', b'Testing'), (b'REQM', b'Requirements management'), (b'CONTROL', b'Monitoring and control')], max_length=100)),
                ('total_budgeted_effort', models.FloatField()),
                ('planned_effort', models.FloatField()),
                ('real_effort', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efforts', to='tool.Project')),
            ],
        ),
    ]
