# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_effort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effort',
            old_name='total_budgeted_effort',
            new_name='budgeted_effort',
        ),
    ]
