# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_auto_20170818_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effort',
            name='phase',
            field=models.CharField(choices=[(b'START', b'Starting'), (b'REQM', b'Requirements'), (b'PLAN', b'Planning'), (b'DEVT', b'Development'), (b'TEST', b'Testing'), (b'IMPLEMENTATION', b'Implementation'), (b'CONTROL', b'Monitoring and control'), (b'CONFIG', b'Configuration management'), (b'CLOSURE', b'Closure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(choices=[(b'START', b'Starting'), (b'REQM', b'Requirements'), (b'PLAN', b'Planning'), (b'DEVT', b'Development'), (b'TEST', b'Testing'), (b'IMPLEMENTATION', b'Implementation'), (b'CONTROL', b'Monitoring and control'), (b'CONFIG', b'Configuration management'), (b'CLOSURE', b'Closure')], max_length=100),
        ),
    ]
