# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0013_auto_20170818_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[(b'START', b'Starting'), (b'REQM', b'Requirements'), (b'PLAN', b'Planning'), (b'DEVT', b'Development'), (b'TEST', b'Testing'), (b'IMPLEMENTATION', b'Implementation'), (b'CONTROL', b'Monitoring and control'), (b'CONFIG', b'Configuration management'), (b'CLOSURE', b'Closure')], max_length=100)),
                ('budgeted_cost', models.FloatField()),
                ('planned_cost', models.FloatField()),
                ('real_cost', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='tool.Project')),
            ],
        ),
    ]
